name: pyenv
channels:
  - tmap
  - conda-forge
  - defaults
dependencies:
  - ld_impl_linux-64  # [linux]
  - libgcc-ng         # [linux]
  - libstdcxx-ng      # [linux]
  - ncurses           # [linux]
  - readline          # [linux]
  - pip
  - rdkit
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - backcall
  - beautifulsoup4
  - bleach
  - ca-certificates
  - certifi
  - cffi
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - flit-core
  - ipython_genutils
  - jedi
  - jinja2
  - jsonschema
  - jupyterlab_pygments
  - libffi
  - libgomp
  - libsodium
  - markupsafe
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nest-asyncio
  - notebook-shim
  - ogdf
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - prometheus_client
  - psutil
  - ptyprocess
  - pycparser
  - pygments
  - pyparsing
  - python
  - python-dateutil
  - python_abi
  - send2trash
  - setuptools
  - sniffio
  - soupsieve
  - sqlite
  - tinycss2
  - tk
  - tmap
  - traitlets
  - typing_extensions
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xz
  - zeromq
  - zlib
  - pip:
      - absl-py
      - altgraph
      - appdirs
      - astunparse
      - attrs
      - autocommand
      - automat
      - biopython
      - cachetools
      - chardet
      - charset-normalizer
      - cheroot
      - cherrypy
      - chex
      - colour
      - constantly
      - contextlib2
      - cryptography
      - cssselect
      - customtkinter
      - cycler
      - darkdetect
      - dm-haiku
      - dm-tree
      - docker
      - faerun
      - fastjsonschema
      - filelock
      - flatbuffers
      - fonttools
      - gast
      - google-auth
      - google-auth-oauthlib
      - google-pasta
      - grpcio
      - h5py
      - hyperlink
      - idna
      - immutabledict
      - importlib-metadata
      - importlib-resources
      - incremental
      - inflect
      - ipykernel
      - ipython
      - itemadapter
      - itemloaders
      - jaraco-classes
      - jaraco-collections
